const Cert = [
    {src : "https://shubs997.github.io/ignitelaunch/img/logo.png" , name:"M-Pluse Ignite" , subtitle : " Winner Mock Placement" , course:"https://images.vexels.com/media/users/3/129153/isolated/lists/da985521b2ffcbb95a2ca9d3c9f39afa-1st-place-laurel-badge.png"},
    {src : "https://shubs997.github.io/ignitelaunch/img/logo.png" , name:"M-Pluse Ignite" , subtitle : " Winner Bug-Bounty" , course:"https://images.vexels.com/media/users/3/129153/isolated/lists/da985521b2ffcbb95a2ca9d3c9f39afa-1st-place-laurel-badge.png"},
    {src : "https://shubs997.github.io/ignitelaunch/img/logo.png" , name:"M-technophilia " , subtitle : "Runner Up Tech Quiz" , course:"https://cdn3.iconfinder.com/data/icons/rawan/512/Laures4-512.png"},
    {src : "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Association_for_Computing_Machinery_%28ACM%29_logo.svg/1200px-Association_for_Computing_Machinery_%28ACM%29_logo.svg.png" , name:"PES MCOE" , subtitle : "Invicta in Top 10" , course:"https://www.freepnglogos.com/uploads/trophy-png/trophy-award-winner-png-33.png"},
    {src : "https://cdn.worldvectorlogo.com/logos/codio.svg" , name:"Coursera" , subtitle : "C++" , course:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/1822px-ISO_C%2B%2B_Logo.svg.png"},
    {src : "https://logos-world.net/wp-content/uploads/2021/11/Udemy-Logo.png" , name:"Udemy" , subtitle : "CSS For Beginners" , course : "https://upload.wikimedia.org/wikipedia/commons/3/3c/CSS_text_representation_%28square%29.png"},
    {src : "https://logos-world.net/wp-content/uploads/2021/11/Udemy-Logo.png" , name:"Udemy" , subtitle : "JS Fundamentals" , course:"https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png"},
    {src : "https://logos-world.net/wp-content/uploads/2021/11/Udemy-Logo.png" , name:"Udemy" , subtitle : "Photoshop Basics" , course:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Adobe_Photoshop_CC_icon.svg/2101px-Adobe_Photoshop_CC_icon.svg.png" },
    {src : "https://logos-world.net/wp-content/uploads/2021/11/Udemy-Logo.png" , name:"Udemy" , subtitle : "Ubuntu" , course :"https://cdn.icon-icons.com/icons2/1508/PNG/512/distributorlogoubuntu_103999.png"},
    {src : "https://logos-world.net/wp-content/uploads/2021/11/Udemy-Logo.png" , name:"Udemy" , subtitle : "Wordpress" , course:"https://img.freepik.com/free-icon/wordpress_318-183439.jpg?w=360"},
    {src : "https://pbs.twimg.com/profile_images/1641476962362302464/K8lb6OtN_400x400.jpg" , name:"AWS" , subtitle : "Cloud Foundations" , course:"https://cantina.co/images/blog/2012-01-25-automated-dns-for-aws-instances-using-route-53/square.png"},
    {src : "https://pbs.twimg.com/profile_images/1641476962362302464/K8lb6OtN_400x400.jpg" , name:"AWS" , subtitle : "Machine Learning" , course:"https://www.outsystems.com/Forge_CW/_image.aspx/Q8LvY--6WakOw9afDCuuGaCS0KExXhCZHt2P29wjJec=/aws-machine-learning-connector-2023-01-04%2000-00-00-2023-04-01%2016-59-31"},
    {src : "https://media.licdn.com/dms/image/C4D0BAQFy7zAItEc-AA/company-logo_200_200/0/1656678293271?e=2147483647&v=beta&t=3RsS7eeoFubqUAgLzbZ-02MHRDa2saDzBR5bGF7z6fU" , name:"Congnizant" , subtitle : "AI" , course:"https://img.freepik.com/premium-vector/ai-technology-digital-artificial-intelligence-future-circuit-electronic-colorful-vector-logo-design_216988-1080.jpg"},
    {src : "https://media.licdn.com/dms/image/C4D0BAQFy7zAItEc-AA/company-logo_200_200/0/1656678293271?e=2147483647&v=beta&t=3RsS7eeoFubqUAgLzbZ-02MHRDa2saDzBR5bGF7z6fU" , name:"Congnizant" , subtitle : "Agile Methodology" , course:"https://www.seguetech.com/wp-content/uploads/2015/08/segue-blog-problems-adopting-agile-development-THUMB.png"},
    {src : "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/HackerRank_logo.png/800px-HackerRank_logo.png" , name:"Hackerrank" , subtitle : "Problem Solving" , course:"https://findvectorlogo.com/wp-content/uploads/2018/09/data-systems-analysts-inc-dsa-vector-logo.png"},
    {src : "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/HackerRank_logo.png/800px-HackerRank_logo.png" , name:"Hackerrank" , subtitle : "Python Basic" , course:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1869px-Python-logo-notext.svg.png"},
    {src : "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/HackerRank_logo.png/800px-HackerRank_logo.png" , name:"Hackerrank" , subtitle : "SQL" , course:"https://db.cs.uni-tuebingen.de/teaching/ws2223/sql-is-a-programming-language/logo.svg"},
    {src : "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Infosys_logo.svg/1280px-Infosys_logo.svg.png" , name:"Infosys" , subtitle : "Machine Learning" , course:"https://www.outsystems.com/Forge_CW/_image.aspx/Q8LvY--6WakOw9afDCuuGaCS0KExXhCZHt2P29wjJec=/aws-machine-learning-connector-2023-01-04%2000-00-00-2023-04-01%2016-59-31"},
    {src : "https://yt3.googleusercontent.com/5GRqKBAh297QftejDogw1Sr23bE7AkIDYehTTwTxk5FIdIY-7W9GQx-HWDWtjUiqTLFJc0CtoFg=s900-c-k-c0x00ffffff-no-rj" , name:"Spoken Tutorial" , subtitle : "R Programming" , course:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/R_logo.svg/2560px-R_logo.svg.png"},
    {src : "https://yt3.googleusercontent.com/5GRqKBAh297QftejDogw1Sr23bE7AkIDYehTTwTxk5FIdIY-7W9GQx-HWDWtjUiqTLFJc0CtoFg=s900-c-k-c0x00ffffff-no-rj" , name:"Spoken Tutorial" , subtitle : "C Programming" , course:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/C_Programming_Language.svg/1200px-C_Programming_Language.svg.png"},
    ];

    export default Cert;